### ISSUE TITLE
Distant rectangles still being scanned

### ISSUE THREAD

**Issue by TheSisb** [elbywan/quadtree-lib#10]
Hi, great lib!

I was playing with the example and noticed that distant rectangles were still being scanned:
![image](https://user-images.githubusercontent.com/1592327/35201945-1767e0de-fed4-11e7-928f-55bfd7d62b5e.png)
Adding more elements reveals the pattern 
![image](https://user-images.githubusercontent.com/1592327/35201948-21962674-fed4-11e7-9630-41f8ff932d0c.png)

Without diving into the code too heavily I was wondering if it would be possible to add some kind of 'distance' coefficient so that oversized rectangles on distant axes nodes (not quite sure of the actual term) aren't brought into the computation?

`quadtree = root -> [NW,NE,SW,SE] where each direction is itself a quadtree.`
For collisions you check for nearby 'leafs', but only recurse upwards to a certain point based on the descendant quadrant positioning.

Example:

```
☐ ☐ ☐ ☐ | ☐ ☐ ☐ ☐
☐ ☐ ☐ ☐ | ☐ ☐ ☐ ☐
☐ ☐ ☐ ☐ | ☐ ☐ ☐ ☐
☐ ☐ ☐ ☐ | ☐ ☐ ☐ ☐
-----------------
☐ ☐ ☐ ☐ | ☐ ☐ ☐ ☐
☐ ☐ ☐ ☐ | ☐ ☐ ☐ ☐
☐ ☐ ☐ ☐ | ☐ ☐ ☐ ☐
☐ ☐ ☐ ☐ | ☐ ☐ ☐ ☐

☐ ☐ | ☐ ☐ | ☐ ☐ ☐ ☐
☐ ☐ | ☐ ☐ | ☐ ☐ ☐ ☐
--------- |
☐ ☐ | ☐ ☐ | ☐ ☐ ☐ ☐
☐ ☐ | ☐ ☐ | ☐ ☐ ☐ ☐
-----------------
☐ ☐ ☐ ☐ | ☐ ☐ ☐ ☐
☐ ☐ ☐ ☐ | ☐ ☐ ☐ ☐
☐ ☐ ☐ ☐ | ☐ ☐ ☐ ☐
☐ ☐ ☐ ☐ | ☐ ☐ ☐ ☐

Here, if we're in the NW quadrant inside the NW quadrant (2 levels deep) we 
can omit the oversized rectangles on the root node axes.  
```

**Comment by elbywan** [comment]
> Hi, great lib!

Thanks a bunch ! 😄 

> Without diving into the code too heavily I was wondering if it would be possible to add some kind of 'distance' coefficient so that oversized rectangles on distant axes nodes (not quite sure of the actual term) aren't brought into the computation?

Unfortunately I think that it would be quite impossible to do that. In the demo you are seeing small "oversized" elements that stick to the axes (which seems convenient), but those "oversized" elements can be much bigger (up to the whole quadtree size - or bigger in the case of the root quadtree).  

So even if you are checking an element which is located in the top left corner for collisions, it could theorically conflict with any "oversized" element (up to the root of the quadtree). The only way to know that is to check every one of them out !

You're right by the way, "oversized" might be the wrong word to describe them 😉 . "Oversized" elements are simply elements that do not fit inside a given quadtree and that expand out of the quadtree boundaries.

**Comment by TheSisb** [comment]
Good point I didn't consider. Thanks for the explanation!
