### ISSUE TITLE
tree.children[contentDir] is undefined; can't access its "get" property

### ISSUE THREAD

**Issue by jefferson-julio** [elbywan/quadtree-lib#11]
There's this error when I try to push objects in the quadtree, it only happens when I push more objects than the number maxElement variable has.

**Comment by elbywan** [comment]
Hi @JJaeger-Ackerman,

I cannot reproduce on my end purely by pushing more than `maxElement` (https://runkit.com/elbywan/5bdaa85c85947c001433e872).

Could you possibly share more details like how you insert elements, the full quadtree configuration and the value of you elements? The error might be related to something else.

**Comment by jefferson-julio** [comment]
Well, it appears that the error vanished. After some time I just tested if the error persisted and it doesn't shows anymore. Sorry for the trouble, but the universe solved it :relieved:

**Comment by elbywan** [comment]
> Sorry for the trouble, but the universe solved it 😌

Well good news then 😉. Thanks for letting me know!
