### ISSUE TITLE
Adding custom properties (Typescript)

### ISSUE THREAD

**Issue by IonelLupu** [elbywan/quadtree-lib#4]
It is possible to add custom properties to QuadtreeItems like this, which is fine:
```javascript
let item = { x: 50, y: 50, width: 10, height: 10,  color: "red" }
```

In Typescript, when I use, for example, this method to find a node:
```javascript
tree.find(function(element){
    return element.data.color === 'red' //Example 
});
```
It gives me the error: `Property 'data' does not exist on type 'QuadtreeItem'`

You can do something like this in the definition file:
```javascript

declare namespace Quadtree {
    export type QuadtreeItem = { x: number, y: number, width?: number, height?: number,[x: string]: any }
}
```
By adding `[x: string]: any` the user can add any property to the QuadtreeItem and the compiler won't complain about.

Or maybe there are other methods to solve this.

Thank you!

**Comment by elbywan** [comment]
Hello @JCWolf,

You're absolutely right the `QuadtreeItem`type was too strong and I just [fixed](https://github.com/elbywan/quadtree-lib/commit/5da28915ccd1d5412bb30e1c7baf199400d9ffe0) the issue according to your suggestion. 

Thanks a lot for the tip 👍 !
