### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by Arcanorum** [elbywan/quadtree-lib#5]
You should try commenting your code.
I'm staring at your code, but I don't have a clue what you are doing.
There is no implementation documentation.

**Comment by elbywan** [comment]
> You should try commenting your code.
> I'm staring at your code, but I don't have a clue what you are doing.

I suppose that you are looking at the .js files. 

For your information, quadtree-lib is written in Coffeescript, which is then transpiled to Javascript. This process strips comments.

The real source code is [fully commented.](https://github.com/elbywan/quadtree-lib/blob/master/src/quadtree.coffee)
[There is even a docco page if you prefer.](http://elbywan.github.io/quadtree-lib/)
