### ISSUE TITLE
Return both collidees with onCollision

### ISSUE THREAD

**Issue by Arcanorum** [elbywan/quadtree-lib#7]
```javascript
onCollision({
    x: 10,
    y: 20
}, function(item1, ->item2<-) {
    /* Action on colliding items */

    // As with all iterative methods, modifying the quadtree or its contents is discouraged. //
}, function(element1, element2){
    /* Optional custom collision algorithm */
    return // Place predicate here //
}) 
```

```coffeescript
for elt in top.oversized when elt isnt item and collisionFunction item, elt then callback ->item<-, elt
for elt in top.contents  when elt isnt item and collisionFunction item, elt then callback ->item<-, elt
```

I think the callback for onCollision should be passed both items involved in the collision, not just the other one, so stuff can also be done with the first object, like the collisionFunction. Only being passed the other item is too limiting.

**Comment by elbywan** [comment]
```coffeescript
for elt in top.oversized when elt isnt item and collisionFunction item, elt then callback ->item<-, elt
```

If you look at the code, you already provide `->item<-` as the first argument of the `onCollision`method.

In your example, its value is : 
```javascript
{
    x: 10,
    y: 20
}
```

It just feels awkward in my opinion to duplicate in a callback a variable that you are already providing as an argument. 
And it would be a **breaking change** since the first argument would not be `elt` but `item` (to keep it consistent with the `collisionFunction`).

If you want to access it you can rewrite your example this way :
```javascript
var collision = { x: 10, y: 20 }

qtree.onCollision(collision, function(colliding) {
    // collision is your "item1"
    // colliding is your "item2"
}) 
```

Or :

```javascript
var collision = { x: 10, y: 20 }
var callback = function(collision) {
    return function(colliding) {
        // collision is your "item1"
        // colliding is your "item2"
    }
}

qtree.onCollision(collision, callback(collision))
```
 -----

The reason why I passed 2 elements to the `collisionFunction` is that it feels more natural for a predicate function to have two arguments to compare (like the [Array.sort](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) function). 

And it also makes the function reusable.

**Comment by Arcanorum** [comment]
I don't fully understand.

> If you look at the code, you already provide `->item<-` as the first argument of the `onCollision`method.

But there isn't an easy way to access `->item<-` from the first callback.

I don't mean duplicate any object. I just want to references to **both** items that have collided to be given to the callback as arguments.

Where you say I could do
```javascript
var collision = { x: 10, y: 20 }

qtree.onCollision(collision, function(colliding) {
    // collision is your "item1"
    // colliding is your "item2"
}) 
```
would only work if I already know the `collision` item and have defined it somewhere easy to access.
If I store all of my items in an array, then I'll need to know the index of that particular item, which can't be done with your code. It would be so much easier if we were just given a reference to the "item1" as well as the "item2" inside of the callback, so it would work for any 2 items that collide, without knowing where or how they are stored.

Just assuming that `colliding` is the only item that users care about is a bad idea. We are often interested in both items.

**Comment by elbywan** [comment]
>  I just want to references to both items

I'm sorry, which **two items** are you referring to ?

> I just want to references to both items that have collided to be given to the callback as arguments.

I think there is a misunderstanding about the fact that there are not **two items** that collide.

I will try to explain a little bit better :

There is a **"zone"** that you pass to the onCollision method ({x: 10, y: 20}, eventually a width and a height). And there is are **items** that collide with the **"zone"**. Each callback call has one of these colliding items as an argument.

The zone is not necessarily an item contained in the quadtree.

The **"zone"** is your reference. What you call "both items" is always **the same "zone"** and a **different item** for each callback.

> would only work if I already know the collision item and have defined it somewhere easy to access.

You are forced to know it. It is the first argument that you pass to the onCollision method.

**Comment by Arcanorum** [comment]
Thanks for explaining.
Now I see that the first parameter isn't actually an element in the tree as such, which is where my confusion came from. I see how this is better, as we can define an arbitrary area to check for collisions with.
