### ISSUE TITLE
When to use onCollision?

### ISSUE THREAD

**Issue by Arcanorum** [elbywan/quadtree-lib#8]
I've noticed that none of your examples use onCollision, instead manually looping through colliding elements like
```
movementTick: function() {
            var that = this
            this.elts.forEach(function(elt) {
                var collisions = that.quadtree.colliding(elt)
                if(elt.x < 0) {
                    if(elt.direction[0] < 0)
                        elt.direction[0] = -elt.direction[0]
                    elt.x = 0
                } else if(elt.x + elt.width > width) {
                    if(elt.direction[0] > 0)
                ....
```
which seems a bit redundant.

When should someone loop through `.colliding` like you do, versus setting `.onCollision` callbacks?

**Comment by elbywan** [comment]
> manually looping through colliding elements

In the code sample you posted, I am not looping through the colliding elements.
I am looping through **all** elements to detect potential collisions and act accordingly by changing an element direction and color.

The reason why I iterate on a separate array is that you cannot modify a quadtree while iterating on it (an unfortunate but inherent limitation of the quadtree data structure). And by modifying I mean adding / removing elements.

> When should someone loop through .colliding like you do, versus setting .onCollision callbacks?

Use `colliding` if you need to work on an array of colliding items.
Use `onCollision ` if you do not need an array allocation and just need an action performed for each colliding item. (see #3)
